backend/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :deals
  resources :roles
	root 'home#index'

	devise_for :users, path: 'auth', controllers: {
			confirmations: 'users/confirmations',
			passwords: 'users/passwords',
			registrations: 'users/registrations',
			sessions: 'users/sessions',
	}

	devise_scope :user do
		get 'sign_out' => 'users/sessions#destroy'
		#get 'sign_in' => 'users/sessions#new'
		#get 'sign_up' => 'users/registrations#new'
		post 'users' => 'users/registrations#create'
		post 'sign_in' => 'users/sessions#create'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :users
	resources :posts
	get 'looged_in_user' => 'users#looged_in_user'
	get '/*path' => 'home#index'
end

backend/app/models/deal.rb
class Deal < ApplicationRecord
	has_many :orders, :dependent => :destroy
	validates :title, presence: true
	validates :description, presence: true
	validates :quantity, presence: true
	validates :price, presence: true
	validates :discounted_price, presence: true
	validates :publish_date, presence: true
end

backend/app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
    start_time = DateTime.now.in_time_zone('Asia/Kolkata')
    start_time = start_time.change({ hour: 10, min: 0, sec: 0 })
    end_time = start_time + 1.day
    deal = @deals.where(publish_date: start_time..end_time)
    render :json => deal, status: :ok
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    start_time = deal_params[:publish_date].to_time.in_time_zone('Asia/Kolkata')
    start_time = start_time.change({ hour: 10, min: 0, sec: 0 })
    end_time = start_time + 1.day
    @deal.publish_date = start_time
    if Deal.where(publish_date: start_time..end_time).blank? and @deal.save
        render :json => @deal, :status => :created
    else
      render :json => @deal.errors, :status => :unprocessable_entity
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :description, :price, :discounted_price, :quantity, :publish_date, :image_path, :string)
    end
end

backend/app/helpers/deals_helper.rb
module DealsHelper
end

backend/app/views/deals/_form.html.erb
<%= form_for(deal) do |f| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :discounted_price %>
    <%= f.text_field :discounted_price %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :publish_date %>
    <%= f.text_field :publish_date %>
  </div>

  <div class="field">
    <%= f.label :image_path %>
    <%= f.text_field :image_path %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

backend/app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Discounted price</th>
      <th>Quantity</th>
      <th>Publish date</th>
      <th>Image path</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.title %></td>
        <td><%= deal.description %></td>
        <td><%= deal.price %></td>
        <td><%= deal.discounted_price %></td>
        <td><%= deal.quantity %></td>
        <td><%= deal.publish_date %></td>
        <td><%= deal.image_path %></td>
        <td><%= deal.string %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>

backend/app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

backend/app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @deal.price %>
</p>

<p>
  <strong>Discounted price:</strong>
  <%= @deal.discounted_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @deal.quantity %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @deal.publish_date %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @deal.image_path %>
</p>

<p>
  <strong>String:</strong>
  <%= @deal.string %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>